import { Inter } from "next/font/google";
import { Noto_Sans_Mono } from "next/font/google"
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });
const noto = Noto_Sans_Mono({ subsets: ["latin"], weight: '400' });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={noto.className}>{children}</body>
    </html>
  );
}
